import Head from "next/head"
import { BsFillMoonStarsFill } from "react-icons/bs"
import {
  AiFillLinkedin,
  AiFillInstagram,
  AiFillTwitterCircle,
} from "react-icons/ai"
import Image from "next/image"
import deved from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import web1 from "../public/web01.png"
import web2 from "../public/web02.png"
import web3 from "../public/web03.png"
import web4 from "../public/web04.png"
import web5 from "../public/web05.png"
import web6 from "../public/web06.png"
import { useState } from "react"
import Link from "next/link"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Roshan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="px-10 bg-white md:px-20 lg:px-40 dark:bg-gray-900">
        {/* section with navbar */}
        <section className="min-h-screen">
          <nav className="flex justify-between py-10 mb-12">
            <h1 className="text-xl font-burtons dark:text-white">
              DevelopbyRoshan
            </h1>
            <ul className="flex items-center">
              <li className="list-none">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="text-2xl cursor-pointer dark:text-white"
                />
              </li>
              <li>
                <a
                  href="https://docs.google.com/document/d/1O-Qtqdoo78x73hYMrL8_7dNIXXzAXaku/edit?usp=sharing&ouid=113995107266914876097&rtpof=true&sd=true"
                  className="px-4 py-2 ml-8 text-white rounded-md bg-gradient-to-r from-cyan-500 to-teal-500"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          {/* Your Intro */}
          <div className="p-10 text-center">
            <h2 className="text-5xl font-medium text-teal-600 md:text-6xl">
              Roshan
            </h2>
            <h3 className="py-2 text-2xl md:text-3xl dark:text-white">
              Frontend Developer
            </h3>
            <p className="max-w-xl py-5 mx-auto font-semibold leading-8 text-gray-800 text-md md:text-xl dark:text-white">
              Freelancing providing services for programming needs. Join me
              let's turn your ideas into reality.
            </p>
          </div>
          <div className="flex justify-center gap-16 py-3 text-5xl">
            {/* <AiFillTwiiterCircle /> */}
            <Link
              legacyBehavior
              href={"https://www.instagram.com/roshan_i_can/"}
            >
              <a>
                <AiFillInstagram className="dark:text-white" />
              </a>
            </Link>
            {/* Linkdln */}
            <Link
              legacyBehavior
              href={"https://www.linkedin.com/in/roshan-ican/"}
            >
              <a>
                <AiFillLinkedin className="dark:text-white" />
              </a>
            </Link>
            {/* twitter */}
            <Link legacyBehavior href={"https://twitter.com/IamMuha51906610"}>
              <a>
                <AiFillTwitterCircle className="dark:text-white" />
              </a>
            </Link>
          </div>
          <div className="relative mx-auto mt-20 overflow-hidden rounded-full bg-gradient-to-b from-teal-500 w-80 h-80 md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover" alt="profile" />
          </div>
        </section>
        {/* section 2 */}
            
        <section>
          <div>
            <h3 className="py-1 text-3xl dark:text-white">Services I offer</h3>
            <p className="py-2 leading-8 text-gray-800 text-md dark:text-white">
              Since the beginning of my journey as a freelancer developer, I've
              done remote work for various startups, mostly with MERN Stack.
              <br />
              <span className="text-teal-500"> Agencies </span>
              consulted for <span className="text-teal-500"> startups </span>
              and collaborated with talented people to create digital products
              E-commerce, Blockchain and Admin applications for both business
              and consumer use.
            </p>
            <p className="py-2 leading-8 text-gray-800 text-md dark:text-white">
              I offer a wide range of services from web development to digital
              marketing, consultation
            </p>
          </div>
          <div className="gap-10 lg:flex">
            {/* card  1*/}
            <div className="flex flex-col items-center justify-center p-10 mx-auto my-10 text-center shadow-lg rounded-xl">
              <Image
                src={design}
                width={100}
                height={100}
                className="justify-center"
                alt="designIcon"
              />
              <h3 className="pt-8 pb-2 text-lg font-medium dark:text-white">
                Beautiful Designs
              </h3>
              <p className="font-medium dark:text-white">
                Design that suits for your needs
              </p>
              <h4 className="py-4 font-bold text-teal-600">
                Technologies that I use
              </h4>
              <p className="py-1 text-gray-800 uppercase dark:text-white">
                Figma
              </p>
              <p className="py-1 text-gray-800 uppercase dark:text-white">
                Photoshop CC and Coral Draw
              </p>
              <p className="py-1 text-gray-800 uppercase dark:text-white">
                Illustrator
              </p>
            </div>
            {/* card 2 */}
            <div className="flex flex-col items-center justify-center p-10 mx-auto my-10 text-center shadow-lg  rounded-xl">
              <Image
                src={code}
                width={100}
                height={100}
                className="justify-center"
                alt="codeIcon"
              />
              <h3 className="pt-8 pb-2 text-lg font-medium dark:text-white">
                Fast and Responsive Website
              </h3>
              <p className="font-medium dark:text-white">
                Creating elegant websites suited for your needs
              </p>
              <h4 className="py-4 font-bold text-teal-600">
                Technologies that I use
              </h4>
              <p className="py-1 text-gray-800 uppercase dark:text-white">
                Javascript, React JS, Next Js
              </p>
              <p className="py-1 text-gray-800 uppercase dark:text-white">
                HTML, CSS, BOOTSTRAP, TAILWINDCSS
              </p>
              <p className="py-1 text-gray-800 uppercase dark:text-white">
                Node Js, Django, Express Js, Firebase
              </p>
            </div>
            {/*card 3 */}
            <div className="flex flex-col items-center justify-center p-10 mx-auto my-10 text-center shadow-lg  rounded-xl">
              <Image
                src={consulting}
                width={100}
                height={100}
                className="justify-center"
                alt="designIcon"
              />
              <h3 className="pt-8 pb-2 text-lg font-medium dark:text-white">
                Consulting that helps you grow
              </h3>
              <p className="font-medium dark:text-white">
                Experience based advices
              </p>
              {/* <h4 className="py-4 font-bold text-teal-600">Technologies that I use</h4>
              <p className="py-1 text-gray-800 uppercase dark:text-white">
                Javascript, React JS, Next Js
              </p>
              <p className="py-1 text-gray-800 uppercase dark:text-white">
                HTML, CSS, BOOTSTRAP, TAILWINDCSS
              </p>
              <p className="py-1 text-gray-800 uppercase dark:text-white">
                Node Js, Django, Express Js, Firebase
              </p> */}
            </div>
          </div>
        </section>
        {/* dark mode */}
        <section>
          <div>
            <h3 className="py-1 text-3xl dark:text-white">Portfolio</h3>
            <p className="py-2 leading-8 text-gray-800 text-md dark:text-white">
              Since the beginning of my journey as a freelancer developer, I've
              done remote work for various startups, mostly with MERN Stack.
              <span className="text-teal-500">
                <br />
                Agencies{" "}
              </span>
              consulted for <span className="text-teal-500">startups </span>
              and collaborated with talented people to create digital products
              Mostly E-commerce, Blockchain and Admin applications for both
              business and consumer use.
            </p>
            <p className="py-2 leading-8 text-gray-800 text-md dark:text-white">
              I offer a wide range of services from web development to digital
              marketing, consultation
            </p>
          </div>
          {/* projects section */}
          <div className="flex flex-col py-15 lg:flex-row lg:flex-wrap">
            <div className="flex-1 p-4 basis-1/3">
              <Link href={"https://amazona-gamma.vercel.app/"} legacyBehavior>
                <a>
                  <Image
                    src={web1}
                    className="object-cover w-full h-full rounded-lg"
                    layout="responsive"
                    alt="Amazona"
                  />
                </a>
              </Link>
            </div>
            <div className="flex-1 p-4 basis-1/3">
              <Link
                href={"https://roshan-ican.github.io/SpaceX/"}
                legacyBehavior
              >
                <a>
                  <Image
                    src={web2}
                    className="object-cover w-full h-full rounded-lg"
                    layout="responsive"
                    alt="Space-x"
                  />
                </a>
              </Link>
            </div>
            <div className="flex-1 p-4 basis-1/3">
              <Link
                href={
                  "https://roshan-ican.github.io/BootStrap-Bootcamp-website.github.io"
                }
                legacyBehavior
              >
                <a>
                  <Image
                    src={web3}
                    className="object-cover w-full h-full rounded-lg"
                    layout="responsive"
                    alt="BootCamp website"
                  />
                </a>
              </Link>
            </div>
            <div className="flex-1 p-4 basis-1/3">
              <Link legacyBehavior href={"https://flickoot.netlify.app/"}>
                <a>
                  <Image
                    src={web4}
                    className="object-cover w-full h-full rounded-lg"
                    layout="responsive"
                    alt="AOT platform"
                  />
                </a>
              </Link>
            </div>
            <div className="flex-1 p-4 basis-1/3">
              <Link href={"#"} legacyBehavior>
                <a>
                  <Image
                    src={web5}
                    className="object-cover w-full h-full rounded-lg"
                    layout="responsive"
                    alt="Blockchain"
                  />
                </a>
              </Link>
            </div>
            <div className="flex-1 p-4 basis-1/3">
              <Link
                href={"https://roshan-ican.github.io/webapp.github.io/"}
                legacyBehavior
              >
                <a>
                  <Image
                    src={web6}
                    className="object-cover w-full h-full rounded-lg"
                    layout="responsive"
                    alt="Marketing-agency"
                  />
                </a>
              </Link>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
